# Generated by Django 5.0.6 on 2024-11-19 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("skills", models.CharField(blank=True, max_length=255)),
                ("goals", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                ("achievements", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("linkedin_profile", models.URLField(blank=True)),
                ("github_profile", models.URLField(blank=True)),
                ("is_expert", models.BooleanField(default=False)),
                ("mentor_since", models.DateField(blank=True, null=True)),
                (
                    "mentorship_areas",
                    models.TextField(
                        blank=True,
                        help_text="Areas you're willing to mentor in, separated by commas",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="Your general availability for mentoring",
                        max_length=255,
                    ),
                ),
                (
                    "preferred_mentoring_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., One-on-one, Group sessions, Online, In-person",
                        max_length=100,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="profiles_pr_user_id_3364d1_idx")
                ],
                "unique_together": {("user",)},
            },
        ),
    ]
