# Generated by Django 5.1.3 on 2025-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_availability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github_profile",
            field=models.URLField(blank=True, null=True),
        ),
    ]
