# Generated by Django 5.0.6 on 2024-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0004_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github_profile",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_expert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_profile",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
