# Generated by Django 5.0.6 on 2024-07-29 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masteryhub", "0012_remove_cartitem_cart_remove_cartitem_session_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="checkout.cart"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masteryhub.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=32, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=50)),
                ("street_address1", models.CharField(max_length=80)),
                ("street_address2", models.CharField(blank=True, max_length=80)),
                ("county", models.CharField(blank=True, max_length=80)),
                ("town_or_city", models.CharField(max_length=80)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(max_length=40)),
                ("phone_number", models.CharField(max_length=20)),
                ("order_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("skills", models.CharField(blank=True, max_length=255)),
                ("goals", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                ("achievements", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("linkedin_profile", models.URLField(blank=True)),
                ("github_profile", models.URLField(blank=True)),
                ("is_expert", models.BooleanField(default=False)),
                ("mentor_since", models.DateField(blank=True, null=True)),
                (
                    "mentorship_areas",
                    models.TextField(
                        blank=True,
                        help_text="Areas you're willing to mentor in, separated by commas",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="Your general availability for mentoring",
                        max_length=255,
                    ),
                ),
                (
                    "preferred_mentoring_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., One-on-one, Group sessions, Online, In-person",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="masteryhub.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkout.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="checkout_pr_user_id_352aa1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together={("user",)},
        ),
    ]
