# Generated by Django 5.1.3 on 2024-12-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
        ("masteryhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="sessions",
            field=models.ManyToManyField(
                blank=True, related_name="carts", to="masteryhub.session"
            ),
        ),
    ]
