# Generated by Django 5.1.3 on 2024-12-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_cart_sessions"),
        ("masteryhub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="sessions",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "session")},
        ),
    ]
