# Generated by Django 5.1.3 on 2025-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
