# Generated by Django 5.1.3 on 2025-03-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_order_stripe_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
