# Generated by Django 5.0.6 on 2024-08-09 13:42

import django_countries.fields
from django.db import migrations
from django_countries.fields import CountryField


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_alter_order_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=CountryField(blank_label="Country *", null=False, blank=False, max_length=40),
        ),
    ]
