# Generated by Django 5.1.3 on 2025-04-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0007_order_status_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="stripe_pid",
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="webhook_processed",
            field=models.BooleanField(default=False),
        ),
    ]
