# Generated by Django 5.0.6 on 2024-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="goals",
            field=models.TextField(blank=True),
        ),
    ]
