# Generated by Django 5.1.3 on 2024-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
