# Generated by Django 5.1.3 on 2024-12-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0003_mentorshiprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="masteryhub.category",
            ),
        ),
    ]
