# Generated by Django 5.0.6 on 2024-07-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0004_alter_forum_author_alter_mentorship_mentee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcernReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inappropriate_behavior", "Inappropriate Behavior"),
                            ("technical_issue", "Technical Issue"),
                            ("content_quality", "Content Quality"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
