# Generated by Django 5.0.6 on 2024-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0005_concernreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
