# Generated by Django 5.0.6 on 2024-07-22 09:43

from django.db import migrations


def set_session_prices(apps, schema_editor):
    Session = apps.get_model("masteryhub", "Session")
    Session.objects.filter(title="Machine Learning Basics").update(price=49.99)
    Session.objects.filter(title="Advanced JavaScript Techniques").update(price=59.99)
    Session.objects.filter(title="Introduction to Digital Marketing").update(
        price=39.99
    )


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0006_session_price"),
    ]

    operations = [
        migrations.RunPython(set_session_prices),
    ]
