# Generated by Django 5.1.4 on 2025-02-12 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0007_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
