# Generated by Django 5.1.3 on 2025-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0008_session_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="price",
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
        ),
    ]
