# Generated by Django 5.0.6 on 2024-07-25 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0009_alter_session_date_alter_session_duration_cart_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=32, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=50)),
                ("street_address1", models.CharField(max_length=80)),
                ("street_address2", models.CharField(blank=True, max_length=80)),
                ("county", models.CharField(blank=True, max_length=80)),
                ("town_or_city", models.CharField(max_length=80)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(max_length=40)),
                ("phone_number", models.CharField(max_length=20)),
                ("order_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
