# Generated by Django 5.1.3 on 2025-03-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0009_alter_session_price"),
        ("profiles", "0003_alter_profile_github_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions_hosted",
                to="profiles.profile",
            ),
        ),
    ]
