# Generated by Django 5.0.6 on 2024-07-27 08:43

from django.db import migrations


def add_more_categories(apps, schema_editor):
    Category = apps.get_model("masteryhub", "Category")

    categories = [
        {"name": "Graphic Design", "description": "Learn graphic design skills"},
        {"name": "Data Science", "description": "Learn data science skills"},
        {"name": "Leadership", "description": "Develop leadership skills"},
        {
            "name": "Time Management",
            "description": "Improve your time management skills",
        },
        {"name": "Career Development", "description": "Advance your career"},
    ]

    for category in categories:
        Category.objects.get_or_create(name=category["name"], defaults=category)


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0010_order"),
    ]

    operations = [
        migrations.RunPython(add_more_categories),
    ]
