# Generated by Django 5.1.3 on 2025-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0010_alter_session_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
