# Generated by Django 5.0.6 on 2024-07-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "masteryhub",
            "0011_remove_forumpost_author_remove_forumpost_category_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
