# Generated by Django 5.0.6 on 2024-08-02 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("masteryhub", "0011__add_more_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="session",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="session",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.profile"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions_hosted",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_feedbacks",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="mentorship",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentorships_as_mentor",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mentee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="mentorship",
            name="mentee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentorships_as_mentee",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="forum",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.profile"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="sessions_participated", to="accounts.profile"
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
