# Generated by Django 5.0.6 on 2024-07-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0012_delete_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="availability",
            field=models.CharField(
                blank=True,
                help_text="Your general availability for mentoring",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="mentor_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mentorship_areas",
            field=models.TextField(
                blank=True,
                help_text="Areas you're willing to mentor in, separated by commas",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_mentoring_method",
            field=models.CharField(
                blank=True,
                help_text="e.g., One-on-one, Group sessions, Online, In-person",
                max_length=100,
            ),
        ),
    ]
