# Generated by Django 5.1.3 on 2025-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0012_update_session_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=99.99,
                help_text="Session price in USD",
                max_digits=10,
            ),
        ),
    ]
