# Generated by Django 5.0.6 on 2024-07-08 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0013_profile_availability_profile_mentor_since_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorship",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentorship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mentorship",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
