# Generated by Django 5.1.3 on 2025-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0013_alter_session_price"),
        ("profiles", "0003_alter_profile_github_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                db_table="masteryhub_session_participants",
                related_name="sessions_participated",
                to="profiles.profile",
            ),
        ),
    ]
