# Generated by Django 5.0.6 on 2024-07-13 06:30

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('masteryhub', '0014_mentorship_created_at_mentorship_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('experience', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('linkedin_profile', models.URLField(blank=True)),
                ('github_profile', models.URLField(blank=True)),
                ('is_expert', models.BooleanField(default=False)),
                ('mentor_since', models.DateField(blank=True, null=True)),
                ('mentorship_areas', models.TextField(blank=True, help_text="Areas you're willing to mentor in, separated by commas")),
                ('availability', models.CharField(blank=True, help_text='Your general availability for mentoring', max_length=255)),
                ('preferred_mentoring_method', models.CharField(blank=True, help_text='e.g., One-on-one, Group sessions, Online, In-person', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]