# Generated by Django 5.0.6 on 2024-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0014_mentorship_created_at_mentorship_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="session_images/"),
        ),
    ]
