# Generated by Django 5.1.3 on 2025-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0016_alter_session_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorship",
            name="last_session_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorship",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Private notes about this mentorship"
            ),
        ),
        migrations.AddField(
            model_name="mentorship",
            name="session_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mentorship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mentorship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
