# Generated by Django 5.1.3 on 2025-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0017_mentorship_last_session_date_mentorship_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("SESSION_BOOKED", "Session Booked"),
                    ("SESSION_COMPLETED", "Session Completed"),
                    ("REVIEW_ADDED", "Review Added"),
                    ("GOAL_ACHIEVED", "Goal Achieved"),
                    ("MENTORSHIP_REQUESTED", "Mentorship Requested"),
                    ("MENTORSHIP_ACCEPTED", "Mentorship Accepted"),
                    ("MENTORSHIP_REJECTED", "Mentorship Rejected"),
                    ("MENTORSHIP_CANCELLED", "Mentorship Cancelled"),
                    ("MENTORSHIP_COMPLETED", "Mentorship Completed"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
