# Generated by Django 5.1.3 on 2025-03-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0019_auto_20250318_1049"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="forum",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_posts",
                to="masteryhub.category",
            ),
        ),
    ]
