# Generated by Django 5.1.3 on 2025-03-31 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masteryhub", "0021_order"),
        ("profiles", "0003_alter_profile_github_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forum",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="forum",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_posts",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="forum",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_posts",
                to="masteryhub.category",
            ),
        ),
        migrations.AlterField(
            model_name="forum",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="masteryhub.forum",
            ),
        ),
        migrations.AlterField(
            model_name="forum",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masteryhub_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
