from django.urls import path, include
from . import views
from .views import (
    expert_dashboard,
    mentee_dashboard,
    mentor_matching_view,
    forum_list,
    create_forum_post,
    view_forum_post,    
    book_session,
    edit_session,
    session_list,
    become_mentor,
    mentor_help,
    report_concern,
    mentor_rules,
    request_mentorship,
    manage_mentorship_requests,
    accept_mentorship,
    reject_mentorship,
    cancel_mentorship_request,
    my_mentorships,
    view_session,
    create_session,
    delete_session,
    review_list,
    create_review,
    booking_success,
    view_mentor_profile,
    list_mentors,
    edit_forum_post,
    delete_forum_post,
    my_orders,
    my_learning,
    search_mentors,
    create_feedback,
    enroll_session,
    browse_skills,
    matching_results,
)

app_name = 'masteryhub'

urlpatterns = [
    path('home/', include('home.urls', namespace='home')),
    path('reviews/', review_list, name='review_list'),
    path('reviews/create/<int:session_id>/',
         create_review, name='create_review'),
    path('browse-skills/', browse_skills, name='browse_skills'),
    path('checkout/', include('checkout.urls')),
    # Mentors
    path('mentors/', list_mentors, name='list_mentors'),
    path('mentor/<str:username>/', view_mentor_profile,
         name='view_mentor_profile'),
    path('search-mentors/', search_mentors, name='search_mentors'),
    path("become-mentor/", become_mentor, name="become_mentor"),
    path("mentor-help/", mentor_help, name="mentor_help"),
    path("mentor-rules/", mentor_rules, name="mentor_rules"),
    # Mentorship
    path("expert-dashboard/", expert_dashboard, name="expert_dashboard"),
    path("mentee-dashboard/", mentee_dashboard, name="mentee_dashboard"),
    path("mentor-matching/", mentor_matching_view, name="mentor_matching"),
    path("matching-results/", matching_results, name='matching_results'),
    path("request-mentorship/<int:mentor_id>/",
         request_mentorship, name="request_mentorship"),
    path("request-mentorship/profile/<int:profile_id>/", 
        request_mentorship, name="request_mentorship_profile"),
    path("manage-mentorship-requests/", manage_mentorship_requests,
         name="manage_mentorship_requests"),
    path("accept-mentorship/<int:mentorship_id>/",
         accept_mentorship, name="accept_mentorship"),
    path("reject-mentorship/<int:mentorship_id>/",
         reject_mentorship, name="reject_mentorship"),
    path("cancel-mentorship-request/<int:request_id>/",
         cancel_mentorship_request, name="cancel_mentorship_request"),
    path("my-mentorships/", my_mentorships, name="my_mentorships"),
    path("report-concern/", report_concern, name="report_concern"),
    # Sessions
    path("session/<int:session_id>/", view_session, name="view_session"),
    path("sessions/", session_list, name="session_list"),
    path("sessions/create/", create_session, name="create_session"),
    path("sessions/<int:session_id>/edit/", edit_session, name="edit_session"),
    path("sessions/<int:session_id>/delete/",
         delete_session, name="delete_session"),
    path("sessions/<int:session_id>/feedback/", create_feedback, name='create_feedback'),
    path("session/<int:session_id>/book/", book_session, name="book_session"),
    path("session/<int:session_id>/enroll/",
         enroll_session,
         name='enroll_session'),
    # Forums
    path("forums/", forum_list, name="forum_list"),
    path("forums/create/", create_forum_post, name="create_forum_post"),
    path("forums/<int:post_id>/", view_forum_post, name="view_forum_post"),
    path("forums/<int:post_id>/edit/", edit_forum_post, name='edit_forum_post'),
    path("forums/<int:post_id>/delete/", delete_forum_post, name='delete_forum_post'),
    path('my-orders/', my_orders, name='my_orders'),
    path('my-learning/', my_learning, name='my_learning'),
    path('booking/success/', booking_success, name='booking_success'),
    path("create-session/", views.create_session, name="create_session"),
]
